### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by soluxSG** [leblanc-simon/odoo-attachment-preview#2]
Dear friend. I found this module and I cloned, I correctly installed this but I don´t know how to use. Do you define a new widget for this? or use a standard widget of odoo? I ask you this becose I don't see any diference in my views of attachments.

Thanks.

**Comment by felipe2323** [comment]
Hi Dear Friend , 
I also download and install the module, but I can not find the way to use it. thank you very much.

**Comment by soluxSG** [comment]
Just reboot your computer. Be carefully with the name of module.

**Comment by felipe2323** [comment]
hi dear friend @soluxSG, I restart the computer however I still do not see anything in 'ir.attachment' model form view ; a question in which version of odoo you tried it  ? thank you very much

**Comment by cristinamartinrod** [comment]
Was the same for me, but I solved with 'reboot'. Thanks for the module!!

**Comment by leblanc-simon** [comment]
Hi all,

this module is only tested with Odoo 8 and Odoo 10.
Be carreful with the name of module, it must be : attachment_preview
If reload module is not enough, restart Odoo service.
